//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./module_types');
//HELPER FUNCTIONS AND STRUCTURES

var setup_init_args = function(args) {
  this.initParame = null;
  if (args) {
    if (args.initParame !== undefined && args.initParame !== null) {
      this.initParame = new ttypes.InitParame(args.initParame);
    }
  }
};
setup_init_args.prototype = {};
setup_init_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.initParame = new ttypes.InitParame();
        this.initParame.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_init_args.prototype.write = function(output) {
  output.writeStructBegin('setup_init_args');
  if (this.initParame !== null && this.initParame !== undefined) {
    output.writeFieldBegin('initParame', Thrift.Type.STRUCT, 1);
    this.initParame.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setup_init_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.GetKeypairs(args.success);
    }
  }
};
setup_init_result.prototype = {};
setup_init_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GetKeypairs();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_init_result.prototype.write = function(output) {
  output.writeStructBegin('setup_init_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setup_execEnc_args = function(args) {
  this.enc = null;
  if (args) {
    if (args.enc !== undefined && args.enc !== null) {
      this.enc = new ttypes.Enc(args.enc);
    }
  }
};
setup_execEnc_args.prototype = {};
setup_execEnc_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.enc = new ttypes.Enc();
        this.enc.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_execEnc_args.prototype.write = function(output) {
  output.writeStructBegin('setup_execEnc_args');
  if (this.enc !== null && this.enc !== undefined) {
    output.writeFieldBegin('enc', Thrift.Type.STRUCT, 1);
    this.enc.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setup_execEnc_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.RetEnc(args.success);
    }
  }
};
setup_execEnc_result.prototype = {};
setup_execEnc_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RetEnc();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_execEnc_result.prototype.write = function(output) {
  output.writeStructBegin('setup_execEnc_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setup_execDec_args = function(args) {
  this.dec = null;
  if (args) {
    if (args.dec !== undefined && args.dec !== null) {
      this.dec = new ttypes.Dec(args.dec);
    }
  }
};
setup_execDec_args.prototype = {};
setup_execDec_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.dec = new ttypes.Dec();
        this.dec.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_execDec_args.prototype.write = function(output) {
  output.writeStructBegin('setup_execDec_args');
  if (this.dec !== null && this.dec !== undefined) {
    output.writeFieldBegin('dec', Thrift.Type.STRUCT, 1);
    this.dec.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setup_execDec_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.RetDec(args.success);
    }
  }
};
setup_execDec_result.prototype = {};
setup_execDec_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RetDec();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

setup_execDec_result.prototype.write = function(output) {
  output.writeStructBegin('setup_execDec_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var setupClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
setupClient.prototype = {};
setupClient.prototype.seqid = function() { return this._seqid; };
setupClient.prototype.new_seqid = function() { return this._seqid += 1; };

setupClient.prototype.init = function(initParame, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_init(initParame);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_init(initParame);
  }
};

setupClient.prototype.send_init = function(initParame) {
  var output = new this.pClass(this.output);
  var params = {
    initParame: initParame
  };
  var args = new setup_init_args(params);
  try {
    output.writeMessageBegin('init', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

setupClient.prototype.recv_init = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new setup_init_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('init failed: unknown result');
};

setupClient.prototype.execEnc = function(enc, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_execEnc(enc);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_execEnc(enc);
  }
};

setupClient.prototype.send_execEnc = function(enc) {
  var output = new this.pClass(this.output);
  var params = {
    enc: enc
  };
  var args = new setup_execEnc_args(params);
  try {
    output.writeMessageBegin('execEnc', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

setupClient.prototype.recv_execEnc = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new setup_execEnc_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('execEnc failed: unknown result');
};

setupClient.prototype.execDec = function(dec, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_execDec(dec);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_execDec(dec);
  }
};

setupClient.prototype.send_execDec = function(dec) {
  var output = new this.pClass(this.output);
  var params = {
    dec: dec
  };
  var args = new setup_execDec_args(params);
  try {
    output.writeMessageBegin('execDec', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

setupClient.prototype.recv_execDec = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new setup_execDec_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('execDec failed: unknown result');
};
var setupProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
setupProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
setupProcessor.prototype.process_init = function(seqid, input, output) {
  var args = new setup_init_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.init.length === 1) {
    Q.fcall(this._handler.init.bind(this._handler),
      args.initParame
    ).then(function(result) {
      var result_obj = new setup_init_result({success: result});
      output.writeMessageBegin("init", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("init", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.init(args.initParame, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new setup_init_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("init", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("init", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
setupProcessor.prototype.process_execEnc = function(seqid, input, output) {
  var args = new setup_execEnc_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.execEnc.length === 1) {
    Q.fcall(this._handler.execEnc.bind(this._handler),
      args.enc
    ).then(function(result) {
      var result_obj = new setup_execEnc_result({success: result});
      output.writeMessageBegin("execEnc", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("execEnc", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.execEnc(args.enc, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new setup_execEnc_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("execEnc", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("execEnc", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
setupProcessor.prototype.process_execDec = function(seqid, input, output) {
  var args = new setup_execDec_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.execDec.length === 1) {
    Q.fcall(this._handler.execDec.bind(this._handler),
      args.dec
    ).then(function(result) {
      var result_obj = new setup_execDec_result({success: result});
      output.writeMessageBegin("execDec", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("execDec", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.execDec(args.dec, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new setup_execDec_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("execDec", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("execDec", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
